--- 

# This is a test role for practicing installing firewalld and
# opening up all relevant ports need for a specific service.
#
#
#
 - name: Install the firewallD service
   yum: name=firewalld state=present

 - name: Mask Iptables and Ip6tables
   systemd: name={{ item }} masked=yes
   with_items:
     - iptables
     - ip6tables

 - name: Enable and start the firewalld service
   service: name=firewalld state=started enabled=yes

 - name: Enable the required firewalld ports on the default zone
   firewalld: 
     port: "{{ item }}"
     permanent: true
     zone: "{{ firewalld_zone }}"
     immediate: yes
     state: enabled
   with_items:
     - "{{ firewalld_ports }}"
