--- # This is a playbook to install rabbitmq and all dependencies

- hosts: localhost
  connection: local
  gather_facts: False
  become: yes

  tasks:
    
    - name: Include variable folder
      include_vars:
        dir: config

    - pip:
        name: 
          - boto
          - boto3
          - botocore

    - name: Provision the base image 
      ec2:
         key_name: ecsWorkKeyPair
         aws_access_key: "{{ec2_access_key}}"
         aws_secret_key: "{{ec2_secret_key}}"
         group: ansible-test
         region: eu-west-2
         instance_type: t2.micro
         image: ami-0274e11dced17bb5b
         wait: true
         exact_count: 1
         count_tag:
            Name: rabbitmq
         instance_tags:
            Name: rabbitmq
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=rabbitmq
      loop: "{{ ec2.instances }}"

    - pause: seconds=20

- hosts: rabbitmq
  name: configure instances
  connection: ssh
  remote_user: ec2-user
  gather_facts: true
  become: yes
  vars:
    ansible_ssh_private_key_file: ~/.ssh/ecsWorkKeyPair.pem
  
  roles:
    - aws_prereqs
    - aws_firewalld
    - aws_rabbitmq

